### PR TITLE
Updates CryptoSwift to 1.0

### PR DESCRIPTION
**Pull request by rommex**
Let's upgrade ))

### CODE REVIEW

**Comment by merenkoff** [comment]
@shamatar Could we get an updated version?

**Comment by shamatar** [comment]
@rommex There is no CI here, so I need your word that tests pass

**Comment by rommex** [comment]
@shamatar Both EthereumAddress and EthereumABI give successful tests -- just checked.

Please update starting with EthereumAddress, as it it the lowest dependency.

Thanks for your work!

**Comment by rommex** [comment]
@shamatar Hope you can make tags with new versions and upload the `.podspec` files for both pods soon )

**Comment by shamatar** [comment]
Should be available already

**Pull request merged**
